base_url = "https://c410-f3r.github.io/"
build_search_index = true
compile_sass = true
default_language = "en"
taxonomies = [
    { name = "tags"}
]
title = "Caio's Stuff"

[extra]
navbar = [
    { icon = "/fontawesome/list.svg", url = "/certifications", name = "Certifications" },
]

[markdown.highlighting]
error_on_missing_language = true
theme = "catppuccin-mocha"