base_url = "https://c410-f3r.github.io/"
build_search_index = false
compile_sass = true
default_language = "en"
title = "Caio's Blog"

[extra]
navbar = [
    { icon = "/fontawesome/home.svg", url = "/", name = "Home" },
    { icon = "/fontawesome/question.svg", url = "/about", name = "About" },
    { icon = "/fontawesome/archive.svg", url = "/archive", name = "Archive" },
    { icon = "/fontawesome/school.svg", url = "/courses", name = "Courses" },
    { icon = "/fontawesome/list.svg", url = "/curriculum.pdf", name = "Curriculum" },
]

[markdown]
highlight_code = true